### ISSUE TITLE
Weird confusion plot

### ISSUE THREAD

**Issue by felixbur** [audeering/audplot#19] opened 2021-08-19 12:23 UTC
hi, 
I get this strange confusion plot with this code
```
        sns.set()  # get prettier plots
        labels = ast.literal_eval(glob_conf.config['DATA']['labels'])
        plt.figure()  # figsize=[5, 5]
        plt.title('Confusion Matrix')
        plt.ylabel('UAR')
        audplot.confusion_matrix(self.truths, self.preds)
        # replace labels
        locs, _ = plt.xticks()
        plt.xticks(locs, labels)
        plt.yticks(locs, labels)
        plt.tight_layout()
        print(f'plotting conf matrix to {fig_dir+plot_name}')
        plt.savefig(fig_dir+plot_name)
        plt.close()
```
and this values
truths
[1 2 0 0 1 2 0 2 3 0 0 2 3 0 0 2 0 2 3 0 0 1 1 2 3 0 2 0 2 0]
preds
[0 2 0 1 1 2 0 3 3 0 0 2 3 0 1 2 0 2 2 1 1 0 0 2 3 0 3 0 2 0]
labels
['neutral', 'happy', 'sad', 'angry']

![xgb-exp_0_0_cnf](https://user-images.githubusercontent.com/2063797/130067615-aaded9be-fac9-4b68-9f6c-ae1c6a4ae712.png)

**Comment by hagenw** [comment] 2021-11-03 07:45
With version 1.3.0 I cannot reproduce your example. When executing your code I get:

![test](https://user-images.githubusercontent.com/173624/140023696-e817cb08-6cec-4c96-a4ef-757dc63404c7.png)

We also introduced the `label_aliases` argument, which means your code can be simplified to:

```python
import audplot
import matplotlib.pyplot as plt

truth = [1, 2, 0, 0, 1, 2, 0, 2, 3, 0, 0, 2, 3, 0, 0, 2, 0, 2, 3, 0, 0, 1, 1, 2, 3, 0, 2, 0, 2, 0]
prediction = [0, 2, 0, 1, 1, 2, 0, 3, 3, 0, 0, 2, 3, 0, 1, 2, 0, 2, 2, 1, 1, 0, 0, 2, 3, 0, 3, 0, 2, 0]
label_aliases = {0: 'neutral', 1: 'happy', 2: 'sad', 3: 'angry'}
audplot.confusion_matrix(truth, prediction, label_aliases=label_aliases)
plt.title('Confusion Matrix')
plt.savefig('test.png')
plt.close()
```

I can reproduce your plot by calling
```python
plt.ylim(3.5, 0.5)
```
before storing to the PNG file.

**Comment by hagenw** [comment] 2021-11-17 10:46
Closing as we cannot reproduce the issue.

**Closed by hagenw** 2021-11-17 10:46 UTC
